openapi: 3.0.3
info:
  title: Ecommerce entities
  desccription: Ecommerce entities schema definations
  version: 1.0.0
path: {}
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        price:
          type: number
          format: double
        category:
          type: string
        description:
          type: string
        image:
          type: string